// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.livebetter.domain;

import com.livebetter.domain.Drinks;
import com.livebetter.domain.PersonDrinks;
import java.util.Calendar;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.OneToMany;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;
import org.springframework.format.annotation.DateTimeFormat;

privileged aspect Drinks_Roo_DbManaged {
    
    @OneToMany(mappedBy = "drinkId")
    private Set<PersonDrinks> Drinks.personDrinkss;
    
    @Column(name = "name", length = 45)
    @NotNull
    private String Drinks.name;
    
    @Column(name = "type", length = 45)
    @NotNull
    private String Drinks.type;
    
    @Column(name = "carbohydrates")
    private Long Drinks.carbohydrates;
    
    @Column(name = "proteins")
    private Long Drinks.proteins;
    
    @Column(name = "fat")
    private Long Drinks.fat;
    
    @Column(name = "calories")
    private Long Drinks.calories;
    
    @Column(name = "created_by")
    private Long Drinks.createdBy;
    
    @Column(name = "created_datetime")
    @Temporal(TemporalType.TIMESTAMP)
    @DateTimeFormat(style = "MM")
    private Calendar Drinks.createdDatetime;
    
    @Column(name = "modified_datetime")
    @Temporal(TemporalType.TIMESTAMP)
    @DateTimeFormat(style = "MM")
    private Calendar Drinks.modifiedDatetime;
    
    public Set<PersonDrinks> Drinks.getPersonDrinkss() {
        return personDrinkss;
    }
    
    public void Drinks.setPersonDrinkss(Set<PersonDrinks> personDrinkss) {
        this.personDrinkss = personDrinkss;
    }
    
    public String Drinks.getName() {
        return name;
    }
    
    public void Drinks.setName(String name) {
        this.name = name;
    }
    
    public String Drinks.getType() {
        return type;
    }
    
    public void Drinks.setType(String type) {
        this.type = type;
    }
    
    public Long Drinks.getCarbohydrates() {
        return carbohydrates;
    }
    
    public void Drinks.setCarbohydrates(Long carbohydrates) {
        this.carbohydrates = carbohydrates;
    }
    
    public Long Drinks.getProteins() {
        return proteins;
    }
    
    public void Drinks.setProteins(Long proteins) {
        this.proteins = proteins;
    }
    
    public Long Drinks.getFat() {
        return fat;
    }
    
    public void Drinks.setFat(Long fat) {
        this.fat = fat;
    }
    
    public Long Drinks.getCalories() {
        return calories;
    }
    
    public void Drinks.setCalories(Long calories) {
        this.calories = calories;
    }
    
    public Long Drinks.getCreatedBy() {
        return createdBy;
    }
    
    public void Drinks.setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }
    
    public Calendar Drinks.getCreatedDatetime() {
        return createdDatetime;
    }
    
    public void Drinks.setCreatedDatetime(Calendar createdDatetime) {
        this.createdDatetime = createdDatetime;
    }
    
    public Calendar Drinks.getModifiedDatetime() {
        return modifiedDatetime;
    }
    
    public void Drinks.setModifiedDatetime(Calendar modifiedDatetime) {
        this.modifiedDatetime = modifiedDatetime;
    }
    
}
