// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.livebetter.domain;

import com.livebetter.domain.Meals;
import com.livebetter.domain.PersonMeals;
import java.util.Calendar;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.OneToMany;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;
import org.springframework.format.annotation.DateTimeFormat;

privileged aspect Meals_Roo_DbManaged {
    
    @OneToMany(mappedBy = "mealId")
    private Set<PersonMeals> Meals.personMealss;
    
    @Column(name = "name", length = 45)
    @NotNull
    private String Meals.name;
    
    @Column(name = "type", length = 45)
    @NotNull
    private String Meals.type;
    
    @Column(name = "carbohydrates")
    private Long Meals.carbohydrates;
    
    @Column(name = "proteins")
    private Long Meals.proteins;
    
    @Column(name = "fat")
    private Long Meals.fat;
    
    @Column(name = "calories")
    private Long Meals.calories;
    
    @Column(name = "created_by")
    private Long Meals.createdBy;
    
    @Column(name = "created_datetime")
    @Temporal(TemporalType.TIMESTAMP)
    @DateTimeFormat(style = "MM")
    private Calendar Meals.createdDatetime;
    
    @Column(name = "modified_datetime")
    @Temporal(TemporalType.TIMESTAMP)
    @DateTimeFormat(style = "MM")
    private Calendar Meals.modifiedDatetime;
    
    public Set<PersonMeals> Meals.getPersonMealss() {
        return personMealss;
    }
    
    public void Meals.setPersonMealss(Set<PersonMeals> personMealss) {
        this.personMealss = personMealss;
    }
    
    public String Meals.getName() {
        return name;
    }
    
    public void Meals.setName(String name) {
        this.name = name;
    }
    
    public String Meals.getType() {
        return type;
    }
    
    public void Meals.setType(String type) {
        this.type = type;
    }
    
    public Long Meals.getCarbohydrates() {
        return carbohydrates;
    }
    
    public void Meals.setCarbohydrates(Long carbohydrates) {
        this.carbohydrates = carbohydrates;
    }
    
    public Long Meals.getProteins() {
        return proteins;
    }
    
    public void Meals.setProteins(Long proteins) {
        this.proteins = proteins;
    }
    
    public Long Meals.getFat() {
        return fat;
    }
    
    public void Meals.setFat(Long fat) {
        this.fat = fat;
    }
    
    public Long Meals.getCalories() {
        return calories;
    }
    
    public void Meals.setCalories(Long calories) {
        this.calories = calories;
    }
    
    public Long Meals.getCreatedBy() {
        return createdBy;
    }
    
    public void Meals.setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }
    
    public Calendar Meals.getCreatedDatetime() {
        return createdDatetime;
    }
    
    public void Meals.setCreatedDatetime(Calendar createdDatetime) {
        this.createdDatetime = createdDatetime;
    }
    
    public Calendar Meals.getModifiedDatetime() {
        return modifiedDatetime;
    }
    
    public void Meals.setModifiedDatetime(Calendar modifiedDatetime) {
        this.modifiedDatetime = modifiedDatetime;
    }
    
}
