// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.livebetter.domain;

import com.livebetter.domain.PersonActivities;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect PersonActivities_Roo_Configurable {
    
    declare @type: PersonActivities: @Configurable;
    
}
